#!/bin/bash -eu
#
# Build the pykdump extension for 'crash'
#

CRASH_VERSION=7.2.6
PYTHON_VERSION=3.7.4

function build_crash()
{
	if ! [ -d crash ] ; then
		git clone --depth=1 --branch "${CRASH_VERSION}" https://github.com/crash-utility/crash.git crash
	fi

	cd crash
#	git clean -dxf
	make
	cd ..
}

function build_python()
{
	if ! [ -d python ] ; then
		wget "https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz"
		tar -xaf "Python-${PYTHON_VERSION}.tar.xz"
		rm "Python-${PYTHON_VERSION}.tar.xz"
		mv "Python-${PYTHON_VERSION}" python
	fi

	cd python
#	make clean
	CFLAGS='-fPIC' ./configure --enable-optimizations
	make
	cd ..
}

function build_pykdump()
{
	if ! [ -d pykdump ] ; then
		git clone git://git.code.sf.net/p/pykdump/code pykdump
	fi

	cd pykdump/Extension
	./configure -c "${BUILDDIR}"/crash -p "${BUILDDIR}"/python
	make
	cd ../../
}

if ! [ -d build ]; then
	mkdir build
fi

cd build
BUILDDIR=${PWD}

build_crash
build_python
build_pykdump
