#!/usr/bin/env python3
#
# Copyright (c) 2019 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

import argparse
import sys

from pykdumplib import utils

dump_pagetables_c = utils.arch_import("dump_pagetables_c")

# Auto base detection so that we can use hex numbers
def auto_int(x):
    return int(x, 0)

@utils.add_arg('-m', '--max-addr', metavar='ADDR', type=auto_int, default=0,
               help='Maximum address')
@utils.add_help('Show a pagetable')
def do_show(args):
    """
    Show pagetables
    """
    dump_pagetables_c.ptdump_show(max_addr=args.max_addr)

if __name__ == '__main__':
    aparser = argparse.ArgumentParser()
    utils.add_subcommand_parsers(aparser, sys.modules[__name__])

    aargs = aparser.parse_args()
    aargs.func(aargs)
