#!/usr/bin/env python3
#
# Copyright (c) 2019 Canonical Ltd.
# Copyright (c) 2016 Hewlett-Packard Development Company, L.P.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

import argparse
import sys

from pykdumplib.linux import sysfs
from pykdumplib import utils

# epython is caching imports, so force a reload
from importlib import reload
sysfs = reload(sysfs)
utils = reload(utils)

@utils.add_arg('-a', '--addr', metavar='ADDR', default=None,
               help='Starting node address (defaults to the root node '
               'address)')
@utils.add_arg('-l', '--level', metavar='LEVEL', default=0, type=int,
               help='Max display depth (defaults to 0 (display the whole '
               'tree))')
@utils.add_help('Show sysfs directory tree')
def do_show(args):
    """
    Show sysfs directory tree
    """
    if args.addr is None:
        node = sysfs.Root()
    else:
        node = sysfs.Node(int(args.addr, 16))
    node.pretty_print(level=args.level)

if __name__ == '__main__':
    aparser = argparse.ArgumentParser()
    utils.add_subcommand_parsers(aparser, sys.modules[__name__])

    aargs = aparser.parse_args()
    aargs.func(aargs)
